provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  pycho:
    lang: python3-flask
    handler: ./pycho
    image: theaxer/pycho:latest
  pycho-async:
    lang: python3-quart
    handler: ./pycho-async
    image: theaxer/pycho-async:latest

